modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="simple_hoverboards"
version="1.0.0"
displayName="Simple Hoverboards"
displayURL="https://mcreator.net"
credits="."
authors="greengoblin"
description="."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.simple_hoverboards]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.simple_hoverboards]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




[[mixins]]
    config="mixin.simple_hoverboards.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration